<def f='include/c++/4.9/exception' l='76' type='void std::bad_exception::bad_exception()'/>
