<dec f='include/c++/4.9/bits/functexcept.h' l='105' type='void std::__throw_bad_function_call()'/>
<doc f='include/c++/4.9/bits/functexcept.h' l='103'>// Helpers for exception objects in &lt;functional&gt;</doc>
<use f='include/c++/4.9/functional' l='2438' u='c' c='_ZNKSt8functionIFT_DpT0_EEclES2_'/>
